-- Lightweight Supabase schema for newsletter lite feed.

create table if not exists public.scraped_items (
  id bigint generated by default as identity primary key,
  source text,
  source_type text,
  title text not null,
  url text,
  content text,
  author text,
  published_at timestamptz,
  scraped_at timestamptz,
  engagement jsonb,
  metadata jsonb,
  content_hash text,
  category text,
  inserted_at timestamptz not null default now()
);

create index if not exists idx_scraped_items_published_at on public.scraped_items (published_at desc);
create index if not exists idx_scraped_items_content_hash on public.scraped_items (content_hash);

create table if not exists public.ranked_sections_cache (
  cache_key text primary key,
  payload jsonb not null,
  generated_at timestamptz not null default now()
);

alter table public.scraped_items enable row level security;
alter table public.ranked_sections_cache enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'scraped_items'
      and policyname = 'scraped_items_public_read'
  ) then
    create policy scraped_items_public_read
      on public.scraped_items
      for select
      to anon, authenticated
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ranked_sections_cache'
      and policyname = 'ranked_sections_cache_public_read'
  ) then
    create policy ranked_sections_cache_public_read
      on public.ranked_sections_cache
      for select
      to anon, authenticated
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ranked_sections_cache'
      and policyname = 'ranked_sections_cache_service_write'
  ) then
    create policy ranked_sections_cache_service_write
      on public.ranked_sections_cache
      for all
      to authenticated
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;
end $$;
