"""Fix user model foreign keys

Revision ID: 789a10644274
Revises: 001
Create Date: 2026-02-11 22:40:12.826952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '789a10644274'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breaking_alerts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('breaking_alerts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('breaking_alerts', 'detection_confidence',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.add_column('hookline_queue', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('hookline_queue', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('processed_content', 'visualizations',
               existing_type=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.drop_index(op.f('ix_processed_content_breaking'), table_name='processed_content')
    op.drop_index(op.f('ix_processed_content_category'), table_name='processed_content')
    op.drop_index(op.f('ix_processed_content_published'), table_name='processed_content')
    op.drop_index(op.f('ix_processed_content_status'), table_name='processed_content')
    op.add_column('raw_content', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('raw_content', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_raw_content_status'), table_name='raw_content')
    op.drop_constraint(op.f('raw_content_content_hash_key'), 'raw_content', type_='unique')
    op.add_column('sources', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('sources', 'success_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('100.0'))
    op.add_column('user_feedback', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('user_feedback_content_id_fkey'), 'user_feedback', type_='foreignkey')
    op.drop_constraint(op.f('user_feedback_user_id_fkey'), 'user_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'user_feedback', 'processed_content', ['content_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_feedback', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_reads', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('user_reads_user_id_content_id_key'), 'user_reads', type_='unique')
    op.drop_constraint(op.f('user_reads_content_id_fkey'), 'user_reads', type_='foreignkey')
    op.drop_constraint(op.f('user_reads_user_id_fkey'), 'user_reads', type_='foreignkey')
    op.create_foreign_key(None, 'user_reads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_reads', 'processed_content', ['content_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_saves', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_saves', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('user_saves_user_id_content_id_key'), 'user_saves', type_='unique')
    op.drop_constraint(op.f('user_saves_user_id_fkey'), 'user_saves', type_='foreignkey')
    op.drop_constraint(op.f('user_saves_content_id_fkey'), 'user_saves', type_='foreignkey')
    op.create_foreign_key(None, 'user_saves', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_saves', 'processed_content', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_saves', 'saved_at')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.add_column('vector_embeddings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('velocity_metrics', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('velocity_metrics', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('velocity_metrics', 'velocity_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('velocity_metrics', 'velocity_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_column('velocity_metrics', 'updated_at')
    op.drop_column('velocity_metrics', 'created_at')
    op.drop_column('vector_embeddings', 'updated_at')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.add_column('user_saves', sa.Column('saved_at'.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_saves', type_='foreignkey')
    op.drop_constraint(None, 'user_saves', type_='foreignkey')
    op.create_foreign_key(op.f('user_saves_content_id_fkey'), 'user_saves', 'processed_content', ['content_id'], ['id'])
    op.create_foreign_key(op.f('user_saves_user_id_fkey'), 'user_saves', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('user_saves_user_id_content_id_key'), 'user_saves', ['user_id', 'content_id'])
    op.drop_column('user_saves', 'updated_at')
    op.drop_column('user_saves', 'created_at')
    op.drop_constraint(None, 'user_reads', type_='foreignkey')
    op.drop_constraint(None, 'user_reads', type_='foreignkey')
    op.create_foreign_key(op.f('user_reads_user_id_fkey'), 'user_reads', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_reads_content_id_fkey'), 'user_reads', 'processed_content', ['content_id'], ['id'])
    op.create_unique_constraint(op.f('user_reads_user_id_content_id_key'), 'user_reads', ['user_id', 'content_id'])
    op.drop_column('user_reads', 'updated_at')
    op.drop_constraint(None, 'user_feedback', type_='foreignkey')
    op.drop_constraint(None, 'user_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('user_feedback_user_id_fkey'), 'user_feedback', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_feedback_content_id_fkey'), 'user_feedback', 'processed_content', ['content_id'], ['id'])
    op.drop_column('user_feedback', 'updated_at')
    op.alter_column('sources', 'success_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('100.0'))
    op.drop_column('sources', 'updated_at')
    op.create_unique_constraint(op.f('raw_content_content_hash_key'), 'raw_content', ['content_hash'])
    op.create_index(op.f('ix_raw_content_status'), 'raw_content', ['status'], unique=False)
    op.drop_column('raw_content', 'updated_at')
    op.drop_column('raw_content', 'created_at')
    op.create_index(op.f('ix_processed_content_status'), 'processed_content', ['status'], unique=False)
    op.create_index(op.f('ix_processed_content_published'), 'processed_content', ['published_at'], unique=False)
    op.create_index(op.f('ix_processed_content_category'), 'processed_content', ['category'], unique=False)
    op.create_index(op.f('ix_processed_content_breaking'), 'processed_content', ['is_breaking', 'breaking_score'], unique=False)
    op.alter_column('processed_content', 'visualizations',
               existing_type=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.drop_column('hookline_queue', 'updated_at')
    op.drop_column('hookline_queue', 'created_at')
    op.alter_column('breaking_alerts', 'detection_confidence',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_column('breaking_alerts', 'updated_at')
    op.drop_column('breaking_alerts', 'created_at')
    # ### end Alembic commands ###
